/** Illustrative scenarios, coordinated with the operational scenes. */
export const APPLICATION_DEMOS = [
  {kind:"inventory", headline:"Move the stock.\nProtect the plan.",signal:"Plant 01 crosses its safety threshold on day 6.",evidence:"620 on hand − 380 reserved = 240 transferable units.",action:"Load three 80-unit pallets. Transfer to Plant 01.",result:"240 units transferred; Plant 02 retains its 380-unit plan.",metric:"240 units",sources:"Stock · production plan · transfer policy",asset:"BEARING X90 / TRF-0240",readings:[["Risk horizon","6 days"],["Supplier ETA","21 days"],["Transfer ETA","2 days"]],beats:["Locate stock","Check reserves","Load & transfer"],labels:["Plant 02","Plant 01"]},
  {kind:"demand",headline:"See demand.\nStay ahead.",signal:"West region orders are outpacing the replenishment plan.",evidence:"Orders, point-of-sale demand and stock agree on the gap.",action:"Raise the West DC order by 1,800 units.",result:"The dispatch plan follows demand before stock runs short.",metric:"+1,800",sources:"Orders · POS · replenishment plan",asset:"WEST REGION / REPLENISHMENT",readings:[["Demand","Above plan"],["Stock","Cross-checked"],["Order change","+1,800 units"]],beats:["Sense demand","Compare sources","Replenish"],labels:["Central DC","West region"]},
  {kind:"production",headline:"Find the bottleneck.\nKeep work moving.",signal:"Work queues at Line 03 while Line 02 has capacity.",evidence:"The next three lots can run on the available line.",action:"Resequence the lots before the 14:00 shift.",result:"A revised production sequence balances the two lines.",metric:"14:00",sources:"MES · capacity · production orders",asset:"ORDER PO-2207 / LINE 03",readings:[["Constraint","Line 03"],["Available","Line 02"],["Next shift","14:00"]],beats:["Detect queue","Check capacity","Resequence"],labels:["Line 03","Line 02"]},
  {kind:"maintenance",headline:"Catch the drift.\nPlan the repair.",signal:"A vibration trend points to the drive-end bearing on Line 04.",evidence:"Asset history and the shift plan reveal a Friday service window.",action:"Reserve the window and create a bearing inspection work order.",result:"Maintenance has an asset, a reason and a planned window.",metric:"By Friday",sources:"Vibration · asset history · work orders",asset:"LINE 04 / MOTOR M-041",readings:[["Asset","Drive motor"],["Inspect","Bearing X90"],["Window","Friday"]],beats:["Detect drift","Inspect bearing","Plan service"],labels:["Motor M-041","Service window"]},
  {kind:"risk",headline:"Trace the disruption.\nProtect the delivery.",signal:"A port delay puts Bearing X90 and Seal S02 at risk.",evidence:"Supplier 02 can supply both parts through a viable lane.",action:"Dual-source the affected parts through the alternative lane.",result:"The sourcing plan changes before the delay reaches production.",metric:"2 parts",sources:"Supplier capacity · lead time · logistics",asset:"SUPPLY ROUTE / EXCEPTION 02",readings:[["Primary lane","Delayed"],["Parts at risk","2"],["Alternative","Checked"]],beats:["Locate disruption","Check alternative","Reroute"],labels:["Primary route","Alternative route"]},
  {kind:"sales",headline:"Follow the orders.\nShift the allocation.",signal:"West dealers have stronger demand than their allocation.",evidence:"Dealer orders and available inventory support a regional shift.",action:"Move 12% of allocation to the West dealer network.",result:"More stock goes where the orders are, within allocation policy.",metric:"12%",sources:"Dealer orders · CRM · inventory",asset:"WEST / DEALER ALLOCATION",readings:[["Demand centre","West"],["Orders","Validated"],["Allocation","+12%"]],beats:["Spot imbalance","Check inventory","Reallocate"],labels:["Central distribution","West dealers"]},
  {kind:"customer",headline:"Fourteen cases.\nOne underlying issue.",signal:"Service cases appear separate until their part histories connect.",evidence:"The same bearing links fourteen affected service records.",action:"Group the cases and escalate the shared part issue.",result:"One coordinated response carries the context from all 14 cases.",metric:"14 → 1",sources:"Case history · part records · service context",asset:"SERVICE / BEARING X90",readings:[["Related cases","14"],["Common part","Bearing X90"],["Escalation","One owner"]],beats:["Read cases","Link the part","Coordinate"],labels:["14 cases","One shared part"]},
  {kind:"finance",headline:"Match the records.\nKeep control.",signal:"Three supplier invoices arrive without the goods receipt.",evidence:"The purchase order matches. The required receipt is missing.",action:"Hold the three payments and route the exception for review.",result:"Payment stays on hold until the receipt can be verified.",metric:"3 held",sources:"Invoices · purchase order · goods receipt",asset:"FINANCE / THREE-WAY MATCH",readings:[["Purchase order","Matched"],["Goods receipt","Missing"],["Invoices","3 on hold"]],beats:["Read invoices","Match records","Apply control"],labels:["Purchase order","Payment review"]},
] as const;
export type DemoKind=(typeof APPLICATION_DEMOS)[number]["kind"];
